[package]
name = "mash-rs"
version = "0.0.1"
edition = "2021"
description = "Hashing Algorithms"
repository = "https://github.com/piot/mash-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
